### PR TITLE
Implementation of RRT connect

### PR DESCRIPTION
**Pull request by americast**
Trees evolve from both start and end points.
ping @KgpKubs/path

### CODE REVIEW

**Comment by kvmanohar22** [comment]
@americast  This class acts as the base class and is not to be tampered with. All the other variants of RRT should derive from this base class and are to be implemented.

**Comment by americast** [comment]
@kvmanohar22 The base classes provided are biased towards RRT. Have a look at https://github.com/KgpKubs/RRT/blob/master/include/RRT_implementation.hpp#L159. The bias is towards the end point, which is not to be in RRT Connect (it should vary based on which tree it is emanating from). Similarly, there are many instances of code in the base class which shows they are meant for RRT only, and not RRT connect. It's not possible to implement connect without modifying the base class. On the other hand, it is possible to implement RRT (without Connect), even with the modified base class. So, I guess this base class is "base"-ier than the already implemented base class :stuck_out_tongue: 

Another solution could be to separate out the class used for RRT Connect into separate base classes.

**Comment by americast** [comment]
@kvmanohar22 Made a separate class for Connect, deriving from the original base class. Separated the file for implementation into another file in the latest commit.

**Comment by americast** [comment]
@KgpKubs/path The base class has been modified a bit in order to accommodate both RRT and RRT Connect, in accordance with a short discussion with @gsengupta2810.

**Pull request merged**
